version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'conjugaciones-user'
      POSTGRES_PASSWORD: 'PASSWORD'
      POSTGRES_DB: 'conjugaciones'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  client:
    build: ./client
    container_name: client
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - ./client:/app
      - ./static:/app/dist
    command: ["npm", "run", "start"]

  backend:
    build: ./conjugaciones_api
    restart: on-failure
    container_name: backend
    volumes:
      - ./conjugaciones_api:/app
    depends_on:
      - db
      - client
      - redis
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    volumes:
      - ./static:/www/static
      - ./data/nginx/app.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  redis:
    container_name: redis
    image: redis
