version: "3"
services:
  client:
    build: ./client
    restart: on-failure
    volumes:
      - static:/app/dist
    command: ["npm", "run", "prod"]

  nginx:
    image: nginx
    restart: on-failure
    volumes:
      - static:/www/static
      - ./data/nginx/app.prod.conf:/etc/nginx/nginx.conf
      - certbot-etc: /etc/letsencrypt
      - certbot-var: /var/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
