# Generated by Django 3.0.5 on 2020-04-27 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ES', 'Español'), ('IT', 'Italiano')], max_length=2)),
                ('infinitive', models.CharField(max_length=64, unique=True)),
                ('infinitive_english', models.CharField(max_length=64, unique=True)),
                ('past_participle', models.CharField(max_length=64)),
                ('gerund', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VerbWeighter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_correct', models.IntegerField()),
                ('total_incorrect', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Verb')),
            ],
        ),
        migrations.CreateModel(
            name='VerbConjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(max_length=64)),
                ('form_1s', models.CharField(blank=True, max_length=127, null=True)),
                ('form_2s', models.CharField(blank=True, max_length=127, null=True)),
                ('form_3s', models.CharField(blank=True, max_length=127, null=True)),
                ('form_1p', models.CharField(blank=True, max_length=127, null=True)),
                ('form_2p', models.CharField(blank=True, max_length=127, null=True)),
                ('form_3p', models.CharField(blank=True, max_length=127, null=True)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.Verb')),
            ],
        ),
    ]
