# Generated by Django 3.0.5 on 2020-05-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0003_auto_20200427_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='verbweighter',
            name='times_seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verbweighter',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
