# Generated by Django 3.0.5 on 2020-05-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0004_auto_20200507_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbweighter',
            name='total_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verbweighter',
            name='total_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verbweighter',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=4),
        ),
    ]
