# Generated by Django 3.0.5 on 2020-05-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0005_auto_20200511_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbweighter',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
    ]
